# src/OC/PlatformBundle/Resources/config/services.yml

services:
    cyream_platform.antispam:
        class: Cydream\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50