services:
  oc_platform.antispam:
      class: Cydream\PlatformBundle\Antispam\CydreamAntispam
      arguments:
          - "@mailer"
          - %locale%
          - 50

  oc_platform.email.application_mailer:
      class: Cydream\PlatformBundle\Email\ApplicationMailer
      arguments:
          - "@mailer"

  oc_platform.doctrine_listener.application_creation:
    class: Cydream\PlatformBundle\DoctrineListener\ApplicationCreationListener
    arguments:
      - "@oc_platform.email.application_mailer"
    tags:
      - { name: doctrine.event_listener, event: postPersist }